const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const net = require('node:net');
const { once } = require('node:events');
const { spawn } = require('node:child_process');
const assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE_PATH || 'playwright');
const { sourceProxy } = require('./network.cjs');
const repo = path.resolve(__dirname, '../..');
const artifactDir = process.env.BROWSER_ARTIFACT_DIR || path.join(os.tmpdir(), 'betterlantalk-browser-artifacts');
fs.mkdirSync(artifactDir, { recursive: true });
(async () => {
 const root = fs.mkdtempSync(path.join(os.tmpdir(), 'lantalk-browser-'));
 const server = path.join(root,'server'); fs.mkdirSync(server);
 for (const name of ['server.js','markdown.js','social.js','jiyu.js']) fs.copyFileSync(path.join(repo,'server',name), path.join(server,name));
 fs.symlinkSync(path.join(repo,'client'),path.join(root,'client'),'dir');
 fs.symlinkSync(path.join(repo,'server/node_modules'),path.join(server,'node_modules'),'dir');
 const probe=net.createServer();probe.listen(0,'127.0.0.1');await once(probe,'listening');const port=probe.address().port;await new Promise(r=>probe.close(r));
 const serverBase='http://127.0.0.1:'+port; let userProxy, adminProxy;
 const child=spawn(process.execPath,['server.js'],{cwd:server,env:{...process.env,PORT:String(port),LANTALK_OPEN_BROWSER:'0'},stdio:['ignore','ignore','pipe']});
 let browser; let serverErrors = ''; child.stderr.on('data', data => serverErrors += data);
 try {
  for(let i=0;i<100;i++){try{if((await fetch(serverBase+'/api/health')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
  userProxy=await sourceProxy(port,'127.0.0.3');adminProxy=await sourceProxy(port,'127.0.0.2');
  const base=userProxy.url, adminBase=adminProxy.url;
  browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE_PATH || undefined,headless:true,args:['--no-sandbox']});
  const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write']});
  const page=await context.newPage(); const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base); await page.locator('#auth-button').waitFor(); assert.equal(await page.locator('#messages-container').count(),0);
  await page.screenshot({path:path.join(artifactDir, 'login.png')});
  await page.click('#tab-register');await page.fill('#username-input','browser-test');await page.fill('#password-input','browser-test-password');await page.fill('#password2-input','browser-test-password');await page.click('#auth-button');
  await page.waitForFunction(()=>window.chatApp?.isConnected);
  const second=await context.newPage(); second.on('pageerror',e=>errors.push(e.message));await second.goto(base);
  await second.waitForFunction(()=>window.chatApp && window.chatApp.isConnected);
  const source='# Luogu Markdown\n\n$x^2 + y^2 = z^2$\n\n:::info[说明]{open}\n公式、表格与代码都可以在内网预览。\n:::\n\n| A | B |\n| --- | --- |\n| 合并单元格 | < |\n\n```cpp line-numbers lines=2\nint main() {\n    return 0;\n}\n```\n\n脚注[^1]\n\n[^1]: 测试注释';
  await page.click('[data-insert=math]');assert.equal(await page.inputValue('#message-input'),'$x^2 + y^2 = z^2$');
  await page.fill('#message-input',source);
  await page.waitForSelector('#message-preview .katex');
  assert.equal(await page.locator('#message-preview details[open]').count(),1);
  assert.equal(await page.locator('#message-preview td[colspan="2"]').count(),1);
  assert.equal(await page.locator('#message-preview .code-line-highlighted').count(),1);
  await page.locator('#message-preview .luogu-code-copy-btn').click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'int main() {\n    return 0;\n}');
  const shared=await page.evaluate(source=>window.createChatMarkdown({LuoguParser,katex,Prism,DOMPurify})(source,'parity'),source);
  assert.equal(shared, require(path.join(repo,'server/markdown'))(source,'parity'));
  await page.click('#send-button');await second.waitForSelector('.message-content .katex');
  await page.waitForFunction(()=>document.querySelector('#message-input').value==='');
  await page.waitForFunction(()=>!document.querySelector('#message-preview .katex'));
  // Actual browser clipboard image paste with Ctrl+V.
  await page.evaluate(async ()=>{const canvas=document.createElement('canvas');canvas.width=1;canvas.height=1;canvas.getContext('2d').fillRect(0,0,1,1);const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));await navigator.clipboard.write([new ClipboardItem({'image/png':blob})]);});
  await page.focus('#message-input');await page.keyboard.press('Control+V');
  await second.waitForSelector('.msg-image img');await second.waitForFunction(()=>{const img=document.querySelector('.msg-image img');return img.complete&&img.naturalWidth===1;});
  await page.setInputFiles('#file-input',{name:'browser-upload.txt',mimeType:'text/plain',buffer:Buffer.from('browser file test')});
  await second.waitForSelector('.file-entry:has-text("browser-upload.txt")');
  const link=second.locator('.msg-file-card a.dl');await link.waitFor();assert.equal(await (await context.request.get(await link.getAttribute('href'))).text(),'browser file test');
  // Enter is native multiline editing; Ctrl+Enter sends the complete draft.
  await page.fill('#message-input','输入法未完成');
  await page.locator('#message-input').evaluate(el=>el.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',ctrlKey:true,isComposing:true,bubbles:true,cancelable:true})));
  assert.equal(await page.inputValue('#message-input'),'输入法未完成');
  await page.fill('#message-input','keyboard first');await page.locator('#message-input').evaluate(el=>el.setSelectionRange(el.value.length,el.value.length));
  await page.keyboard.press('Enter');await page.keyboard.type('keyboard second');
  assert.equal(await page.inputValue('#message-input'),'keyboard first\nkeyboard second');
  assert.equal(await second.locator('.message-content:has-text("keyboard first")').count(),0);
  await page.keyboard.press('Control+Enter');await second.locator('.message-content:has-text("keyboard first")').waitFor();assert.equal(await page.inputValue('#message-input'),'');
  await page.fill('#message-input','$\\sum_{i=1}^n i = \\frac{n(n+1)}{2}$');await page.waitForSelector('#message-preview .katex');
  await page.fill('#message-input',source);await page.waitForSelector('#message-preview details');await page.screenshot({path:path.join(artifactDir, 'chat-desktop.png')});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  const left = await page.locator('.source-pane').boundingBox();
  const right = await page.locator('.preview-pane').boundingBox();
  assert.ok(left && right && left.x + left.width <= right.x + 1);
  assert.equal(left.y,right.y);assert.equal(left.height,right.height);
  assert.ok(Math.abs(left.width-right.width)<2);
  assert.equal(await page.locator('#preview-toggle').count(),0);
  assert.equal(await page.locator('#line-numbers div').count(),source.split('\n').length);
  assert.equal(await page.locator('#markdown-toolbar [data-insert=code] svg').count(),1);
  assert.equal(await page.locator('#markdown-toolbar [data-insert=table] svg').count(),1);
  assert.equal(await page.locator('#markdown-toolbar [data-insert=bold] strong').textContent(),'B');
  for (const selector of ['#message-input','#message-preview','#send-button']) {const rect=await page.locator(selector).boundingBox();assert.ok(rect && rect.y>=0 && rect.y+rect.height<=1000,selector+' fits viewport');}
  await page.fill('#message-input','选中的内容');await page.locator('#message-input').evaluate(el=>el.setSelectionRange(0,el.value.length));
  await page.click('[data-insert=bold]');assert.equal(await page.inputValue('#message-input'),'**选中的内容**');
  await page.click('[data-insert=undo]');assert.equal(await page.inputValue('#message-input'),'选中的内容');
  await page.click('[data-insert=redo]');assert.equal(await page.inputValue('#message-input'),'**选中的内容**');
  await page.click('[data-insert=undo]');await page.focus('#message-input');await page.keyboard.press('Control+b');assert.equal(await page.inputValue('#message-input'),'**选中的内容**');
  const longSource=Array.from({length:80},(_,i)=>'# Section '+i+'\n\nParagraph '+i).join('\n\n');
  await page.fill('#message-input',longSource);await page.waitForFunction(()=>document.querySelectorAll('#message-preview h1').length===80);
  await page.locator('#message-input').evaluate(el=>{el.scrollTop=el.scrollHeight;});
  await page.waitForFunction(()=>{const preview=document.getElementById('message-preview');return preview.scrollTop>=(preview.scrollHeight-preview.clientHeight)*.98;});
  await page.locator('#message-preview').evaluate(el=>{el.scrollTop=0;});
  await page.waitForFunction(()=>document.getElementById('message-input').scrollTop===0);
  await page.fill('#message-input',source);await page.waitForSelector('#message-preview details');
  await page.locator('#message-input').evaluate(el=>{el.scrollTop=0;});
  await page.waitForFunction(()=>document.getElementById('message-preview').scrollTop===0);
  await page.screenshot({path:path.join(artifactDir, 'chat-split-editor.png')});
  // Resize both editor panes with the dedicated separator, persist it, and clamp to viewport.
  const originalHeight=(await page.locator('#composer-panes').boundingBox()).height;
  const handle=await page.locator('#composer-resize').boundingBox();
  await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2);await page.mouse.down();await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2-80,{steps:8});await page.mouse.up();
  const resizedHeight=(await page.locator('#composer-panes').boundingBox()).height;
  assert.ok(resizedHeight>=originalHeight+70);
  assert.equal((await page.locator('.source-pane').boundingBox()).height,(await page.locator('.preview-pane').boundingBox()).height);
  assert.ok((await page.locator('#messages-container').boundingBox()).height>=120);
  await page.reload();await page.waitForFunction(()=>window.chatApp?.isConnected);await page.waitForFunction(height=>Math.abs(document.getElementById('composer-panes').getBoundingClientRect().height-height)<2,resizedHeight);
  await page.locator('#composer-resize').focus();await page.keyboard.press('ArrowDown');assert.ok((await page.locator('#composer-panes').boundingBox()).height<=resizedHeight-20);
  await page.setViewportSize({width:1440,height:620});await page.waitForTimeout(100);
  const smallFooter=await page.locator('#send-button').boundingBox();assert.ok(smallFooter.y+smallFooter.height<=620);assert.ok((await page.locator('#messages-container').boundingBox()).height>=119);
  await page.setViewportSize({width:1440,height:1000});await page.locator('#composer-resize').dblclick();await page.waitForTimeout(100);assert.ok(Math.abs((await page.locator('#composer-panes').boundingBox()).height-originalHeight)<2);
  // Actual Chromium permission grant and Notification construction (OS popup appearance cannot be observed headlessly).
  await context.grantPermissions(['notifications']);await page.click('#notify-btn');assert.equal(await page.locator('#notify-btn').textContent(),'通知已开启');
  assert.equal(await page.evaluate(()=>{const n=new Notification('API check',{body:'Browser notification smoke'});n.close();return Notification.permission;}),'granted');
  await page.click('#notify-btn');assert.equal(await page.locator('#notify-btn').getAttribute('aria-pressed'),'false');
  console.log('PASS: Enter newline, Ctrl+Enter sending, IME guard, editor pointer/keyboard resizing, persisted height, viewport bounds and real Chromium notification permission/API');
  // Separate admin document and WeChat-style friend flows in actual Chromium.
  assert.equal(await page.locator('#admin-view-btn').isVisible(),false);
  assert.equal(await page.locator('#admin-view').count(),0);
  const adminContext=await browser.newContext({viewport:{width:1440,height:1000}});
  const adminPage=await adminContext.newPage();adminPage.on('pageerror',e=>errors.push(e.message));
  adminPage.on('dialog',dialog=>dialog.accept());
  await adminPage.goto(adminBase);await adminPage.fill('#username-input','admin');await adminPage.fill('#password-input','admin123');await adminPage.click('#auth-button');
  await adminPage.waitForFunction(()=>window.chatApp?.isConnected && window.chatApp.userRole==='superadmin');
  await page.fill('#people-search','admin');await page.locator('#people-search-form button').click();
  await page.locator('#people-results button:has-text("加好友")').click();
  await adminPage.locator('#request-count').filter({hasText:'1'}).waitFor();
  await adminPage.click('#friend-requests-btn');await adminPage.locator('#friend-requests button:has-text("接受")').click();
  await page.waitForFunction(()=>window.chatApp.social.friends.length===1);
  await page.locator('.room-item strong', {hasText:'admin'}).click();
  await page.waitForFunction(()=>window.chatApp.currentRoom.startsWith('dm-'));
  await page.fill('#message-input','**friend-only** $x^2$');await page.keyboard.press('Control+Enter');
  await adminPage.locator('.room-item strong', {hasText:'browser-test'}).click();
  await adminPage.locator('.message-content:has-text("friend-only") .katex').waitFor();
  assert.equal(await adminPage.locator('#user-list .action-row').count(),2);
  await adminPage.click('#admin-view-btn');await adminPage.locator('#admin-room-id').waitFor();
  assert.equal(await adminPage.locator('#message-input').count(),0);
  await adminPage.fill('#admin-room-id','browser-public');await adminPage.fill('#admin-room-name','公开群');await adminPage.selectOption('#admin-room-visibility','public');
  await adminPage.getByRole('button',{name:'创建房间',exact:true}).click();
  await adminPage.locator('#admin-rooms-list .admin-item:has-text("browser-public")').waitFor();
  await adminPage.locator('#jiyu-devices .admin-item:has-text("browser-test")').waitFor();
  assert.ok((await adminPage.locator('#jiyu-devices').textContent()).includes('127.0.0.3'));
  assert.equal(await adminPage.getByRole('button',{name:'绑定设备',exact:true}).count(),0);
  const userToken=await page.evaluate(()=>window.chatApp.authToken);
  const wrongDevice=await adminContext.request.get(adminBase+'/client/chat.js',{headers:{Authorization:'Bearer '+userToken}});
  assert.equal(wrongDevice.status(),403);
  assert.equal(await page.locator('.room-item:has-text("公开群")').count(),0);
  await page.click('#discover-btn');await page.locator('#discover-panel .action-row:has-text("公开群") button').click();
  await page.waitForFunction(()=>window.chatApp.currentRoom==='browser-public');
  const account=adminPage.locator('#admin-accounts-list .admin-item:has-text("browser-test")');
  await account.getByRole('button',{name:'设为管理员',exact:true}).click();
  await page.waitForFunction(()=>window.chatApp.userRole==='admin');assert.equal(await page.locator('#admin-view-btn').isVisible(),true);
  await account.getByRole('button',{name:'取消管理员',exact:true}).click();
  await page.waitForFunction(()=>window.chatApp.userRole==='user');assert.equal(await page.locator('#admin-view-btn').isVisible(),false);
  const forbidden=await context.request.get(base+'/client/admin.js');assert.equal(forbidden.status(),403);
  await adminPage.screenshot({path:path.join(artifactDir, 'social-admin.png')});
  await page.locator('.room-item strong', {hasText:'admin'}).click();await page.waitForFunction(()=>window.chatApp.currentRoom.startsWith('dm-'));
  page.on('dialog',dialog=>dialog.accept());
  await page.locator('#conversation-actions button:has-text("删除好友")').click();await page.waitForFunction(()=>window.chatApp.currentCanSend===false);
  assert.equal(await page.locator('#message-input').isDisabled(),true);
  await page.screenshot({path:path.join(artifactDir, 'wechat-chat.png')});
  // Portrait 9:16 and desktop half-screen keep the editor split without page overflow.
  await page.evaluate(() => window.chatApp.joinRoom('default'));
  await page.waitForFunction(() => window.chatApp.currentRoom === 'default' && !document.getElementById('message-input').disabled);
  const narrowText = '这是用于检查消息气泡宽度的长段落。'.repeat(35);
  await page.fill('#message-input', narrowText); await page.keyboard.press('Control+Enter');
  await page.locator('.message-content').filter({ hasText: narrowText }).waitFor();
  for (const viewport of [{width:960,height:1080}, {width:540,height:960}, {width:720,height:1280}]) {
    await page.setViewportSize(viewport); await page.waitForTimeout(100);
    await page.fill('#message-input', source); await page.locator('#message-preview .katex').waitFor();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, JSON.stringify(viewport));
    const bubble = await page.locator('.message-content').filter({hasText:narrowText}).locator('..').boundingBox();
    const messagesBox = await page.locator('#messages-container').boundingBox();
    assert.ok(bubble.width <= Math.min(messagesBox.width * .78, 521), 'message stays narrow');
    const sourceBox = await page.locator('.source-pane').boundingBox(), previewBox = await page.locator('.preview-pane').boundingBox();
    assert.ok(sourceBox.width >= 170 && previewBox.width >= 170);
    assert.ok(Math.abs(sourceBox.width - previewBox.width) < 2 && sourceBox.x + sourceBox.width <= previewBox.x + 1);
    const sendBox = await page.locator('#send-button').boundingBox(); assert.ok(sendBox.y + sendBox.height <= viewport.height);
    assert.equal(await page.locator('#chat-details').isVisible(), false);
    await page.click('#details-toggle'); await page.locator('#chat-details').waitFor({state:'visible'});
    assert.equal(await page.locator('#user-list .action-row').count(), 2);
    await page.click('#details-close'); assert.equal(await page.locator('#chat-details').isVisible(), false);
    if (viewport.width < 700) {
      assert.equal(await page.locator('#conversation-sidebar').isVisible(), false);
      await page.click('#sidebar-toggle'); await page.locator('#friend-requests-btn').waitFor({state:'visible'});
      await page.locator('.room-item strong').filter({hasText:'公开群'}).click();
      await page.waitForFunction(() => window.chatApp.currentRoom === 'browser-public');
      assert.equal(await page.locator('#conversation-sidebar').isVisible(), false);
      await page.fill('#message-input','portrait send test'); await page.keyboard.press('Control+Enter');
      await page.locator('.message-content:has-text("portrait send test")').waitFor();
      await page.evaluate(() => window.chatApp.joinRoom('default')); await page.waitForFunction(() => window.chatApp.currentRoom === 'default');
      await page.fill('#message-input',source); await page.locator('#message-preview .katex').waitFor();
      await page.screenshot({path:path.join(artifactDir,'chat-9x16.png')});
    } else if (viewport.width === 960) await page.screenshot({path:path.join(artifactDir,'chat-half-screen.png')});
  }
  await page.setViewportSize({width:1440,height:1000});await page.waitForTimeout(100);
  assert.equal(await page.locator('#conversation-sidebar').isVisible(),true);assert.equal(await page.locator('#chat-details').isVisible(),true);
  console.log('PASS: 960x1080 half-screen, 540x960 and 720x1280 portrait layouts, narrow bubbles, split panes, drawer navigation, member list and Ctrl+Enter send');
  assert.deepEqual(errors,[]);
  console.log('PASS: fixed account IPs, no manual device binding UI, and cross-IP browser token rejection');
  console.log('PASS: browser preview/server parity, Luogu features, real Ctrl+V PNG, file download, toolbar, undo/redo, scroll sync, friends/request acceptance/DM, separate admin page, explicit public group join, live roles and read-only history after deleting a friend');
 } catch (error) { if (serverErrors) console.error(serverErrors); throw error; } finally {
  if(browser)await browser.close();
  if(userProxy)await userProxy.close();if(adminProxy)await adminProxy.close();
  const stopped=once(child,'exit');child.kill('SIGINT');await stopped;fs.rmSync(root,{recursive:true,force:true});
 }
})().catch(e=>{console.error(e);process.exitCode=1;});
